services:
  slack:
    build:
      context: sre_agent
      dockerfile: servers/slack/Dockerfile
    ports:
      - "8000:3001"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_TEAM_ID=${SLACK_TEAM_ID}
      - TRANSPORT=SSE
  kubernetes:
    build:
      context: sre_agent/servers/kubernetes
      dockerfile: Dockerfile
    ports:
      - "8001:3001"
    volumes:
      - ~/.kube:/home/appuser/.kube
      - ~/.aws:/home/appuser/.aws
    environment:
      - TRANSPORT=SSE
  github:
    build:
      context: sre_agent
      dockerfile: servers/github/Dockerfile
    ports:
      - "8001:3001"
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - TRANSPORT=SSE
  orchestrator:
    build: .
    ports:
      - "8003:80"
