services:
  slack:
    build:
      context: sre_agent
      dockerfile: servers/slack/Dockerfile
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_TEAM_ID=${SLACK_TEAM_ID}
      - TRANSPORT=SSE
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 5s
      timeout: 3s
      retries: 5

  kubernetes:
    build:
      context: sre_agent/servers/mcp-server-kubernetes
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/home/appuser/.aws

    environment:
      - TRANSPORT=SSE
      - AWS_REGION=${AWS_REGION}
      - TARGET_EKS_CLUSTER_NAME=${TARGET_EKS_CLUSTER_NAME}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 5s
      timeout: 3s
      retries: 5
  github:
    build:
      context: sre_agent
      dockerfile: servers/github/Dockerfile
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - TRANSPORT=SSE
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 5s
      timeout: 3s
      retries: 5

  prompt-server:
    build:
      context: .
      dockerfile: sre_agent/servers/prompt_server/Dockerfile
    environment:
      - GITHUB_ORGANISATION=fuzzylabs
      - GITHUB_REPO_NAME=microservices-demo
      - PROJECT_ROOT=src
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 5s
      timeout: 3s
      retries: 5

  llm-server:
    build:
      context: .
      dockerfile: sre_agent/llm/Dockerfile
    environment:
      - PROVIDER=anthropic
      - MODEL=claude-3-7-sonnet-latest
      - MAX_TOKENS=1000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

  llama-firewall:
    build:
      context: .
      dockerfile: sre_agent/firewall/Dockerfile
    environment:
      - HF_TOKEN=${HF_TOKEN}

  orchestrator:
    build:
      context: .
      dockerfile: sre_agent/client/Dockerfile
    ports:
      - "8003:80"

    depends_on:
      llama-firewall:
        condition: service_healthy
      slack:
        condition: service_healthy
      github:
        condition: service_healthy
      kubernetes:
        condition: service_healthy
      prompt-server:
        condition: service_healthy
      llm-server:
        condition: service_healthy

    environment:
      - DEV_BEARER_TOKEN=${DEV_BEARER_TOKEN}
      - QUERY_TIMEOUT=300
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - TOOLS=["list_pods", "get_logs", "get_file_contents", "slack_post_message", "create_issue"]
      - CHANNEL_ID=${CHANNEL_ID}
      - SERVICES=${SERVICES}
