services:
  kubernetes:
    build:
      context: sre_agent/servers/mcp-server-kubernetes
      dockerfile: Dockerfile
    volumes:
      - ~/.config/gcloud:/home/appuser/.config/gcloud
    environment:
      - TRANSPORT=SSE
      - CLOUDSDK_CORE_PROJECT=${CLOUDSDK_CORE_PROJECT}
      - CLOUDSDK_COMPUTE_REGION=${CLOUDSDK_COMPUTE_REGION}
      - GOOGLE_APPLICATION_CREDENTIALS=/home/appuser/.config/gcloud/application_default_credentials.json
      - TARGET_GKE_CLUSTER_NAME=${TARGET_GKE_CLUSTER_NAME}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 5s
      timeout: 3s
      retries: 5

  github:
    build:
      context: sre_agent
      dockerfile: servers/github/Dockerfile
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - TRANSPORT=SSE
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 5s
      timeout: 3s
      retries: 5

  prompt-server:
    build:
      context: .
      dockerfile: sre_agent/servers/prompt_server/Dockerfile
    environment:
      - GITHUB_ORGANISATION=${GITHUB_ORGANISATION}
      - GITHUB_REPO_NAME=${GITHUB_REPO_NAME}
      - PROJECT_ROOT=${PROJECT_ROOT}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 30s
      timeout: 10s
      retries: 3

  llm-server:
    build:
      context: .
      dockerfile: sre_agent/llm/Dockerfile
    environment:
      - PROVIDER=${PROVIDER}
      - MODEL=${MODEL}
      - MAX_TOKENS=${MAX_TOKENS}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  orchestrator:
    build:
      context: .
      dockerfile: sre_agent/client/Dockerfile
    ports:
      - "8003:80"
    depends_on:
      github:
        condition: service_healthy
      kubernetes:
        condition: service_healthy
      prompt-server:
        condition: service_healthy
      llm-server:
        condition: service_healthy
    environment:
      - DEV_BEARER_TOKEN=${DEV_BEARER_TOKEN}
      - QUERY_TIMEOUT=300
      - TOOLS=${TOOLS}
      - SERVICES=${SERVICES}
