apiVersion: v1
kind: Service
metadata:
  name: llm-server
  namespace: sre-agent
spec:
  selector:
    app: llm-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
