apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.sre-orchestrator.appName } }
  namespace: { { .Values.global.namespace } }
  labels:
    app: { { .Values.global.namespace } }
spec:
  replicas: { { .Values.sre-orchestrator.deployment.replicaCount } }
  selector:
    matchLabels:
      app: { { .Values.sre-orchestrator.appName } }
  template:
    metadata:
      labels:
        app: { { .Values.sre-orchestrator.appName } }
    spec:
      containers:
        - name: { { .Values.sre-orchestrator.appName } }
          image: "{{ .Values.global.containerRegistryAddress }}mcp/sre-orchestrator"
          imagePullPolicy:
            {
              {
                .Values.sre-orchestrator.deployment.image.pullPolicy | default "IfNotPresent",
              },
            }
          ports:
            - containerPort:
                { { .Values.sre-orchestrator.deployment.containerPort } }
          env:
            - name: CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: { { .Values.global.secretKeyRef } }
                  key: CHANNEL_ID
            - name: TOOLS
              value: { { .Values.sre-orchestrator.deployment.tools } }
            - name: QUERY_TIMEOUT
              value: { { .Values.sre-orchestrator.deployment.timeout } }
            - name: DEV_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: { { .Values.global.secretKeyRef } }
                  key: DEV_BEARER_TOKEN
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: { { .Values.global.secretKeyRef } }
                  key: SLACK_SIGNING_SECRET
