apiVersion: v1
kind: Service
metadata:
  name: sre-orchestrator-service
  namespace: "{{ .Values.global.namespace }}"
spec:
  selector:
    app: sre-orchestrator
  ports:
    - protocol: TCP
      port: "{{ .Values.sreOrchestrator.service.port }}"
      targetPort: { { .Values.sreOrchestrator.service.targetPort } }
  type: LoadBalancer
