apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-github
  namespace: sre-agent
  labels:
    app: mcp-github
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-github
  template:
    metadata:
      labels:
        app: mcp-github
    spec:
      containers:
        - name: mcp-github
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mcp/github
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: GITHUB_PERSONAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sre-agent-secrets
                  key: GITHUB_PERSONAL_ACCESS_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: github
  namespace: sre-agent
spec:
  selector:
    app: mcp-github
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
