apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-slack
  namespace: sre-agent
  labels:
    app: mcp-slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-slack
  template:
    metadata:
      labels:
        app: mcp-slack
    spec:
      containers:
        - name: mcp-slack
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mcp/slack
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sre-agent-secrets
                  key: SLACK_BOT_TOKEN
            - name: SLACK_TEAM_ID
              valueFrom:
                secretKeyRef:
                  name: sre-agent-secrets
                  key: SLACK_TEAM_ID
---
apiVersion: v1
kind: Service
metadata:
  name: slack
  namespace: sre-agent
spec:
  selector:
    app: mcp-slack
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
