apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-kubernetes-sa
  namespace: sre-agent
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${MCP_ACCESS_ROLE_NAME}
