apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mcp-kubernetes.serviceAccount.name | default "mcp-kubernetes-sa" }}
  namespace: {{ .Values.global.namespace | default "default" }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.awsAccountId }}:role/{{ .Values.mcp-kubernetes.serviceAccount.roleName }}
