apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  namespace: sre-agent
spec:
  selector:
    app: mcp-kubernetes
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
