apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  selector:
    app: mcp-kubernetes
  ports:
    - protocol: TCP
      port: {{ .Values.mcp-kubernetes.service.port | default 3001 }}
      targetPort: {{ .Values.mcp-kubernetes.service.targetPort | default 3001 }}
  type: "ClusterIP"
