name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "fixes/*"
  push:
    branches:
      - main
      - develop

jobs:
  pre-commit:
    name: Pre-commit CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: ".pre-commit-config.yaml"

      - name: Install dependencies
        run: |
          uv sync --group orchestrator --group mcp
          alias pip="uv pip"  # Trick pre-commit to use uv

      - name: Run Pre-commit
        run: |
          uv run pre-commit run --show-diff-on-failure --color=always --all-files
